modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Maciej916/Ma-Essentials/issues"

[[mods]]
    modId="ma-essentials"
    version="${file.jarVersion}"
    displayName="Ma Essentials"
    updateJSONURL="https://raw.githubusercontent.com/Maciej916/Ma-Essentials/1.15.1/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/maessentials"
    logoFile="ma-essentials.png"
    credits=""
    authors="Statywek (Maciej916)"
    description="This mod adds useful commands, homes, kits, warps, server utilities and more..."

    [[dependencies.maessentials]]
        modId="forge"
        mandatory=true
        versionRange="[30.0.14,)"
        ordering="NONE"
        side="BOTH"

    [[dependencies.maessentials]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.14.4]"
        ordering="NONE"
        side="BOTH"