modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Maciej916/Ma-Essentials/issues"

[[mods]]
    modId="ma-essentials"
    version="${file.jarVersion}"
    displayName="Ma Essentials"
    updateJSONURL="https://raw.githubusercontent.com/Maciej916/Ma-Essentials/master/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/maessentials"
    logoFile="ma-essentials.png"
    credits=""
    authors="Maciej916"
    description="This mod adds commands like /sethome, /tpa, /spawn, /day ect."

    [[dependencies.maessentials]]
        modId="forge"
        mandatory=true
        versionRange="[28.1.70,)"
        ordering="NONE"
        side="BOTH"

    [[dependencies.maessentials]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.14.4]"
        ordering="NONE"
        side="BOTH"